
version: '2'

services:
  angular-pwa-seed:
    image: angular-pwa-seed-host
    build:
      context: .
      dockerfile: Dockerfile-host
    environment:
      NODE_ENV: production
    ports:
      - 5555:5555